config/routes.rb
Rails.application.routes.draw do

  resources :menus

  resources :restaurants
  
  resources :nearby_restaurants do
    collection do
      post 'get_by_location'
    end
  end

end

app/models/menu.rb
class Menu < ActiveRecord::Base

	validates :dish, presence: true
	validates :weekday, numericality: {greater_than: 0, less_than: 8}

end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base

	validates :name, presence: true
	validates :price, presence: true, numericality: true
	validates :latitude, presence: true, numericality: true
	validates :longitude, presence: true, numericality: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
  before_action :set_menu, only: [:show, :edit, :update, :destroy]

  # GET /menus
  # GET /menus.json
  def index
    @menus = Menu.all
  end

  # GET /menus/1
  # GET /menus/1.json
  def show
  end

  # GET /menus/new
  def new
    @menu = Menu.new
  end

  # GET /menus/1/edit
  def edit
  end

  # POST /menus
  # POST /menus.json
  def create
    @menu = Menu.new(menu_params)

    respond_to do |format|
      if @menu.save
        format.html { redirect_to @menu, notice: t('.notice') }
        format.json { render :show, status: :created, location: @menu }
      else
        format.html { render :new }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menus/1
  # PATCH/PUT /menus/1.json
  def update
    respond_to do |format|
      if @menu.update(menu_params)
        format.html { redirect_to @menu, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @menu }
      else
        format.html { render :edit }
        format.json { render json: @menu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menus/1
  # DELETE /menus/1.json
  def destroy
    @menu.destroy
    respond_to do |format|
      format.html { redirect_to menus_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_menu
      @menu = Menu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def menu_params
      params.require(:menu).permit(:dish, :weekday)
    end
end

app/controllers/nearby_restaurants_controller.rb
class NearbyRestaurantsController < ApplicationController

  def index
  end
  
  def get_by_location
    @restaurants = []
    @restaurants << '<b><i>Modo de teste!</i></b><br />'
    Restaurant.select(:name,:latitude,:longitude).each do |restaurant|
      #if Geocoder::Calculations.distance_between([params[:latitude],params[:longitude]], [restaurant.latitude, restaurant.longitude]) <= 10.0
      if Geocoder::Calculations.distance_between([98,9], [restaurant.latitude, restaurant.longitude]) <= 10.0
        @restaurants << restaurant.name
      end
    end
    render json: @restaurants
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show, :edit, :update, :destroy]

  # GET /restaurants
  # GET /restaurants.json
  def index
    @restaurants = Restaurant.all
  end

  # GET /restaurants/1
  # GET /restaurants/1.json
  def show
  end

  # GET /restaurants/new
  def new
    @restaurant = Restaurant.new
  end

  # GET /restaurants/1/edit
  def edit
  end

  # POST /restaurants
  # POST /restaurants.json
  def create
    @restaurant = Restaurant.new(restaurant_params)

    respond_to do |format|
      if @restaurant.save
        format.html { redirect_to @restaurant, notice: t('.notice') }
        format.json { render :show, status: :created, location: @restaurant }
      else
        format.html { render :new }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurants/1
  # PATCH/PUT /restaurants/1.json
  def update
    respond_to do |format|
      if @restaurant.update(restaurant_params)
        format.html { redirect_to @restaurant, notice: t('.notice') }
        format.json { render :show, status: :ok, location: @restaurant }
      else
        format.html { render :edit }
        format.json { render json: @restaurant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurants/1
  # DELETE /restaurants/1.json
  def destroy
    @restaurant.destroy
    respond_to do |format|
      format.html { redirect_to restaurants_url, notice: t('.notice') }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurant
      @restaurant = Restaurant.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurant_params
      params.require(:restaurant).permit(:name, :price, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/nearby_restaurants_helper.rb
module NearbyRestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TurboRango</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/menus/_form.html.erb
<%= form_for(@menu) do |f| %>
  <% if @menu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@menu.errors.count, "error") %> prohibited this menu from being saved:</h2>

      <ul>
      <% @menu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dish %><br>
    <%= f.text_area :dish %>
  </div>
  <div class="field">
    <%= f.label :weekday %><br>
    <%= f.number_field :weekday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/menus/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.show'), @menu %> |
<%= link_to t('.back'), menus_path %>

app/views/menus/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.dish') %></th>
      <th><%= t('.weekday') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @menus.each do |menu| %>
      <tr>
        <td><%= menu.dish %></td>
        <td><%= menu.weekday %></td>
        <td><%= link_to t('.show'), menu %></td>
        <td><%= link_to t('.edit'), edit_menu_path(menu) %></td>
        <td><%= link_to t('.destroy'), menu, method: :delete, data: { confirm: t('.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_menu_path %>

app/views/menus/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), menus_path %>

app/views/menus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('.dish') %></strong>
  <%= @menu.dish %>
</p>

<p>
  <strong><%= t('.weekday') %></strong>
  <%= @menu.weekday %>
</p>

<%= link_to t('.edit'), edit_menu_path(@menu) %> |
<%= link_to t('.back'), menus_path %>

app/views/nearby_restaurants/index.html.erb
<h1><%= t('.title') %></h1>


<script>
var html_id_restaurants = document.getElementById('restaurants');

function getLocation() {
  if (navigator.geolocation) {
    navigator.geolocation.getCurrentPosition(showPosition, showError);
  } else {
    alert("<%= t('.browser_not_supported') %>");
  }
}

function showError(error) {
  alert(error.message);
  switch(error.code) {
    case error.PERMISSION_DENIED:
      alert("denied")
      html_id_restaurants.innerHTML = "<%= t('.geo_user_denied') %>";
      break;
    case error.POSITION_UNAVAILABLE:
      html_id_restaurants.innerHTML = "<%= t('.geo_location_unavaliable') %>";
      break;
    case error.TIMEOUT:
      html_id_restaurants.innerHTML = "<%= t('.geo_timeout') %>";
      break;
    case error.UNKNOWN_ERROR:
      html_id_restaurants.innerHTML = "<%= t('.geo_unknow_error') %>";
      break;
  }
}

function showPosition(position) {
  $.ajax({
    type : 'POST',
    url : 'nearby_restaurants/get_by_location',
    data : {
      latitude : position.coords.latitude,
      longitude : position.coords.longitude
    },
    beforeSend : function() {},
    success : function(data) {
      $('#restaurants').empty();
      $.each(data, function(index, restaurant) {
        $('#restaurants').append('<tr><td>' + restaurant + '<td/></tr>');
      });
    },
    allways : function() {}
  });
}

$(document).ready(function() {
  getLocation();
}); 
</script>

<div id='restaurants'>

    <div id="floatingCirclesG">
        <div class="f_circleG" id="frotateG_01"></div>
        <div class="f_circleG" id="frotateG_02"></div>
        <div class="f_circleG" id="frotateG_03"></div>
        <div class="f_circleG" id="frotateG_04"></div>
        <div class="f_circleG" id="frotateG_05"></div>
        <div class="f_circleG" id="frotateG_06"></div>
        <div class="f_circleG" id="frotateG_07"></div>
        <div class="f_circleG" id="frotateG_08"></div>
    </div>

</div>

app/views/restaurants/_form.html.erb
<%= form_for(@restaurant) do |f| %>
  <% if @restaurant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@restaurant.errors.count, "error") %> prohibited this restaurant from being saved:</h2>

      <ul>
      <% @restaurant.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
  <div class="field">
    <%= f.label :latitude %><br>
    <%= f.text_field :latitude %>
  </div>
  <div class="field">
    <%= f.label :longitude %><br>
    <%= f.text_field :longitude %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/restaurants/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.show'), @restaurant %> |
<%= link_to t('.back'), restaurants_path %>

app/views/restaurants/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= t('.name') %></th>
      <th><%= t('.price') %></th>
      <th><%= t('.latitude') %></th>
      <th><%= t('.longitude') %></th>
      <th colspan="3"></th>
    </tr>
  </thead>
  
  <tbody>
    <% @restaurants.each do |restaurant| %>
      <tr>
        <td><%= restaurant.name %></td>
        <td><%= restaurant.price %></td>
        <td><%= restaurant.latitude %></td>
        <td><%= restaurant.longitude %></td>
        <td><%= link_to t('.show'), restaurant %></td>
        <td><%= link_to t('.edit'), edit_restaurant_path(restaurant) %></td>
        <td><%= link_to t('.destroy'), restaurant, method: :delete, data: { confirm: t('.confirm') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('.new'), new_restaurant_path %>

app/views/restaurants/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form' %>

<%= link_to t('.back'), restaurants_path %>

app/views/restaurants/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong><%= t('.name') %></strong>
  <%= @restaurant.name %>
</p>

<p>
  <strong><%= t('.price') %></strong>
  <%= @restaurant.price %>
</p>

<p>
  <strong><%= t('.latitude') %></strong>
  <%= @restaurant.latitude %>
</p>

<p>
  <strong><%= t('.longitude') %></strong>
  <%= @restaurant.longitude %>
</p>

<%= link_to t('.edit'), edit_restaurant_path(@restaurant) %> |
<%= link_to t('.back'), restaurants_path %>